"""The scripted fleet projection: who is registered and what each seat may reach.

Held apart from the incident fixture because it answers a different question —
not what happened, but what is permitted to happen and by whom.
"""

from __future__ import annotations

from typing import Any


def _guidance_entry(
    key: str,
    name: str,
    description: str,
    owner: str,
    kind: str,
    purpose: str,
    agent: str,
    profile: str,
    recorded: str,
    digest: str,
    *,
    available: bool = True,
) -> dict[str, Any]:
    owner_slug, _, skill = key.partition(".")
    if available:
        why = "Built-in product guidance, published by the release process at a pinned commit."
        next_step = "Superseded only by an application release."
    else:
        why = (
            "The revision is approved, but no qualified topology connection is bound in this scope."
        )
        next_step = "Qualify the read connection, then re-run the availability probe."
    return {
        "key": key,
        "version": "1",
        "name": name,
        "description": description,
        "owner": owner,
        "source_kind": "SOLVAN_AUTHORED",
        "source_ref": f"guidance/{owner_slug}/{skill} · pinned release commit",
        "author_principal": "svc:guidance-author@solvan",
        "recorded_at": f"{recorded}T09:00:00+00:00",
        "kind": kind,
        "purpose": purpose,
        "classification": "INTERNAL",
        "regions": ["europe-west1"],
        "agent_keys": [agent],
        "profile_revisions": [profile],
        "lifecycle": "Approved",
        "availability": "Available" if available else "Unavailable",
        "evidence": "Evaluated",
        "why": why,
        "next_step": next_step,
        "revision_hash": digest,
    }


_RELIABILITY = "Reliability Platform"
_PLATFORM = "Platform Engineering"
_PAYMENTS = "Payments SRE"
_DIAGNOSTIC = "Diagnostic procedure"
_LOOKUP = "Focused lookup"
_INVESTIGATION = "Incident investigation"
_CONTEXT = "Investigation context"
_EVIDENCE_PROFILE = "evidence.gcp-core.v1@1"
_TOPOLOGY_PROFILE = "infrastructure.gcp-topology.v1@1"
_REPORT_PROFILE = "reporting.case-records.v1@1"


def _guidance_catalog() -> list[dict[str, Any]]:
    first_party = [
        _guidance_entry(
            "reliability.triage-latency",
            "Triage latency",
            "A bounded, read-only checklist for investigating latency regressions.",
            _RELIABILITY,
            _DIAGNOSTIC,
            _INVESTIGATION,
            "evidence-agent",
            _EVIDENCE_PROFILE,
            "2026-08-10",
            "sha256:dedfd8ecf1d06310",
        ),
        _guidance_entry(
            "reliability.triage-connection-exhaustion",
            "Triage connection exhaustion",
            "The standard triage flow for connection-pool exhaustion: pool utilization, "
            "acquisition wait, timeout signatures, latency, and change correlation.",
            _RELIABILITY,
            _DIAGNOSTIC,
            _INVESTIGATION,
            "evidence-agent",
            _EVIDENCE_PROFILE,
            "2026-08-16",
            "sha256:36a4b9552a85d601",
        ),
        _guidance_entry(
            "reliability.triage-error-rate",
            "Triage error rate",
            "The standard triage flow for a server error-rate spike: ratio shape, "
            "revision split, top signatures, dependencies, and synthetic agreement.",
            _RELIABILITY,
            _DIAGNOSTIC,
            _INVESTIGATION,
            "evidence-agent",
            _EVIDENCE_PROFILE,
            "2026-08-16",
            "sha256:f6d3868828070e37",
        ),
        _guidance_entry(
            "reliability.triage-deployment-regression",
            "Triage deployment regression",
            "The standard triage flow for a regression that began with a rollout: "
            "revision inventory, onset alignment, per-revision metrics, change contents.",
            _RELIABILITY,
            _DIAGNOSTIC,
            _INVESTIGATION,
            "evidence-agent",
            _EVIDENCE_PROFILE,
            "2026-08-16",
            "sha256:443305c12abf84fe",
        ),
        _guidance_entry(
            "reliability.triage-queue-backlog",
            "Triage queue backlog",
            "The standard triage flow for message backlog growth: backlog age, publish "
            "versus ack rates, consumer health, quarantine state, capacity ceilings.",
            _RELIABILITY,
            _DIAGNOSTIC,
            _INVESTIGATION,
            "evidence-agent",
            _EVIDENCE_PROFILE,
            "2026-08-16",
            "sha256:d394b8269198db80",
        ),
        _guidance_entry(
            "reliability.triage-memory-pressure",
            "Triage memory pressure",
            "The standard triage flow for container memory pressure: utilization versus "
            "limit, restart evidence, growth shape, traffic correlation.",
            _RELIABILITY,
            _DIAGNOSTIC,
            _INVESTIGATION,
            "evidence-agent",
            _EVIDENCE_PROFILE,
            "2026-08-16",
            "sha256:b5924f34c6c7e1d2",
        ),
        _guidance_entry(
            "reliability.triage-scaling-stall",
            "Triage scaling stall",
            "The standard triage flow for autoscaling stalls and cold-start pileups: "
            "instance ceilings, concurrency, startup path, denial signatures.",
            _RELIABILITY,
            _DIAGNOSTIC,
            _INVESTIGATION,
            "evidence-agent",
            _EVIDENCE_PROFILE,
            "2026-08-16",
            "sha256:2ce3093c993f7cc2",
        ),
        _guidance_entry(
            "platform.lookup-service-topology",
            "Service topology lookup",
            "Ownership and dependency snapshot for a service: tier, owning team, and "
            "one level of upstream and downstream edges from the frozen snapshot.",
            _PLATFORM,
            _LOOKUP,
            _CONTEXT,
            "infrastructure-agent",
            _TOPOLOGY_PROFILE,
            "2026-08-16",
            "sha256:21a236bcf7974d12",
            available=False,
        ),
        _guidance_entry(
            "platform.lookup-change-history",
            "Change history lookup",
            "Chronological listing of recorded deploys, configuration, and schema "
            "changes in a bounded window around incident onset.",
            _PLATFORM,
            _LOOKUP,
            _CONTEXT,
            "infrastructure-agent",
            _TOPOLOGY_PROFILE,
            "2026-08-16",
            "sha256:dbadf43020638508",
            available=False,
        ),
        _guidance_entry(
            "platform.lookup-quota-saturation",
            "Quota saturation lookup",
            "Utilization against every registered quota and configured limit, with "
            "trend and denial evidence for dimensions above eighty percent.",
            _PLATFORM,
            _LOOKUP,
            _CONTEXT,
            "infrastructure-agent",
            _TOPOLOGY_PROFILE,
            "2026-08-16",
            "sha256:6c6cd29f3525b99d",
            available=False,
        ),
        _guidance_entry(
            "platform.interpret-slo-burn",
            "SLO burn interpretation",
            "Burn-rate interpretation for one objective: definition, short and long "
            "windows, remaining budget, and threshold classification.",
            _PLATFORM,
            _DIAGNOSTIC,
            _INVESTIGATION,
            "evidence-agent",
            _EVIDENCE_PROFILE,
            "2026-08-16",
            "sha256:c3e548f2b15ffc48",
        ),
        _guidance_entry(
            "payments.payments-connection-pool",
            "Payments connection pool knowledge",
            "Workload knowledge for the payments-api pool: intentional backpressure "
            "sizing, the thirty-second lead signal, and the order of reads.",
            _PAYMENTS,
            "Workload knowledge",
            _INVESTIGATION,
            "evidence-agent",
            _EVIDENCE_PROFILE,
            "2026-08-16",
            "sha256:26d0434d06a87c1a",
        ),
        _guidance_entry(
            "payments.payments-checkout-slo",
            "Payments checkout SLO knowledge",
            "Workload knowledge for the checkout objective: endpoint membership, "
            "probe semantics, and traffic shape around breaches.",
            _PAYMENTS,
            "Workload knowledge",
            _INVESTIGATION,
            "evidence-agent",
            _EVIDENCE_PROFILE,
            "2026-08-16",
            "sha256:c1222312abfad43e",
        ),
        _guidance_entry(
            "reporting.incident-summary",
            "Incident summary template",
            "The standard operator-facing incident summary, instantiated only from "
            "cited durable records; unresolved citations render as not established.",
            _RELIABILITY,
            "Report template",
            "Case reporting",
            "workspace-agent",
            _REPORT_PROFILE,
            "2026-08-16",
            "sha256:631937e183ba9c62",
        ),
        _guidance_entry(
            "reporting.postmortem-draft",
            "Postmortem draft template",
            "The permanent-repair postmortem skeleton assembled from case records for "
            "a human owner: timeline, causes, repair, recurrence guards.",
            _RELIABILITY,
            "Report template",
            "Case reporting",
            "workspace-agent",
            _REPORT_PROFILE,
            "2026-08-16",
            "sha256:26dec554c7258ab5",
        ),
    ]
    imported = {
        "key": "payments.connection-exhaustion",
        "version": "1",
        "name": "Payment connection exhaustion",
        "description": (
            "A bounded diagnostic sequence for connection-pool exhaustion; "
            "it grants no action authority."
        ),
        "owner": _PAYMENTS,
        "source_kind": "IMPORTED",
        "source_ref": ("github.com/acme-platform/sre-skills · payments/connection-exhaustion"),
        "author_principal": "user:payments-sre@example.com",
        "recorded_at": "2026-08-12T09:00:00+00:00",
        "kind": _DIAGNOSTIC,
        "purpose": _INVESTIGATION,
        "classification": "INTERNAL",
        "regions": ["europe-west1"],
        "agent_keys": ["evidence-agent"],
        "profile_revisions": ["evidence.ruhu-observability.v1@1"],
        "lifecycle": "Draft",
        "availability": "Unavailable",
        "evidence": "Not evaluated",
        "why": (
            "Imported guidance compiled into a draft awaiting evaluation and independent approval."
        ),
        "next_step": "Complete evaluation, then obtain independent approval.",
        "revision_hash": "sha256:5f21c09ab3d4e876",
    }
    return [*first_party, imported]


def fleet_fixture() -> dict[str, Any]:
    """Return the scripted fleet projection used by the local harness."""

    return {
        "tool_status_definitions": {
            "lifecycle": "Whether this immutable revision may enter new work.",
            "availability": "Whether policy and current connection evidence allow selection here.",
            "evidence": "Whether the exact capability was probed and remains fresh.",
            "deployment": "Implemented, deployed, and release-qualified are separate states.",
        },
        "tools": [
            {
                "key": "cloud_monitoring_read",
                "version": "1",
                "name": "Cloud Monitoring read",
                "owner": "Observability",
                "agent_keys": ["evidence-agent"],
                "agents": ["Evidence Agent"],
                "permission_class": "READ",
                "integration": "Cloud Monitoring",
                "connection": "demo-gcp-europe-west1",
                "lifecycle": "Approved",
                "availability": "Available",
                "evidence": "Probe passed",
                "deployment": "Implemented",
                "registry": "Registered",
                "identity": "evidence-agent identity",
                "gateway": "Bound read route",
                "armor": "Not applicable to typed metric request",
                "region": "europe-west1",
                "last_probe": "Local fixture · 22s ago",
                "probe_expiry": "in 4m 38s",
                "call_budget": 3,
                "timeout_ms": 10000,
                "max_payload_bytes": 65536,
                "last_call": "Succeeded",
                "trace": "trace …a91c",
                "why": "Exact typed Monitoring reads are present in the release implementation.",
                "next_step": "Deploy and capture a bound cloud probe before release qualification.",
            },
            {
                "key": "managed_prometheus_query",
                "version": "1",
                "name": "Managed Prometheus query",
                "owner": "Observability",
                "agent_keys": ["evidence-agent"],
                "agents": ["Evidence Agent"],
                "permission_class": "READ",
                "integration": "Managed Service for Prometheus",
                "connection": "ruhu-prod-europe-west1",
                "lifecycle": "Draft",
                "availability": "Not configured",
                "evidence": "Not probed",
                "deployment": "Implemented",
                "registry": "Local revision only",
                "identity": "Not provisioned",
                "gateway": "Route pending",
                "armor": "Not applicable to registered templates",
                "region": "europe-west1",
                "last_probe": "Never",
                "probe_expiry": "No fresh proof",
                "call_budget": 3,
                "timeout_ms": 10000,
                "max_payload_bytes": 65536,
                "last_call": "Not called",
                "trace": "Not available",
                "why": (
                    "The bounded contract exists, but this Ruhu connection has no "
                    "cloud capability receipt."
                ),
                "next_step": (
                    "Connect Ruhu metrics, grant Monitoring Viewer, and run the exact probe."
                ),
            },
            {
                "key": "github_pr_diff_read",
                "version": "1",
                "name": "GitHub pull-request diff read",
                "owner": "Developer Productivity",
                "agent_keys": ["infrastructure-agent"],
                "agents": ["Infrastructure Agent"],
                "permission_class": "READ",
                "integration": "GitHub App",
                "connection": "github-ruhu-production",
                "lifecycle": "Draft",
                "availability": "Not configured",
                "evidence": "Not probed",
                "deployment": "Implemented",
                "registry": "Local revision only",
                "identity": "Deterministic provider owns credential",
                "gateway": "Provider route pending",
                "armor": "Diff output treated as untrusted",
                "region": "europe-west1",
                "last_probe": "Never",
                "probe_expiry": "No fresh proof",
                "call_budget": 2,
                "timeout_ms": 15000,
                "max_payload_bytes": 131072,
                "last_call": "Not called",
                "trace": "Not available",
                "why": "No bound GitHub repository connection has been qualified for this scope.",
                "next_step": (
                    "Install the GitHub App, bind one repository, and run the read-only probe."
                ),
            },
        ],
        "tool_profiles": [
            {
                "key": "evidence.gcp-core.v1",
                "version": "1",
                "agent_key": "evidence-agent",
                "lifecycle": "Draft",
                "tool_count": 5,
                "connection_count": 1,
                "maximum_calls": 8,
                "region": "europe-west1",
            },
            {
                "key": "infrastructure.gcp-topology.v1",
                "version": "1",
                "agent_key": "infrastructure-agent",
                "lifecycle": "Draft",
                "tool_count": 4,
                "connection_count": 0,
                "maximum_calls": 6,
                "region": "europe-west1",
            },
            {
                "key": "reporting.case-records.v1",
                "version": "1",
                "agent_key": "workspace-agent",
                "lifecycle": "Approved",
                "tool_count": 0,
                "connection_count": 0,
                "maximum_calls": 0,
                "region": "europe-west1",
            },
            {
                "key": "evidence.ruhu-observability.v1",
                "version": "1",
                "agent_key": "evidence-agent",
                "lifecycle": "Draft",
                "tool_count": 6,
                "connection_count": 1,
                "maximum_calls": 12,
                "region": "europe-west1",
            },
        ],
        "tool_probes": [],
        "guidance": _guidance_catalog(),
        "trigger_policies": [],
        "trigger_firings": [],
        "deterministic_services": [
            {
                "name": "Action Actuator",
                "key": "action-actuator",
                "capabilities": "the only production mutation capability",
                "model_backed": False,
                "allowed_operations": [
                    "PAYMENTS_POOL_RECYCLE",
                    "CLOUD_RUN_TRAFFIC_ROLLBACK",
                ],
                "identity": "actuator@",
                "region": "europe-west1",
            },
        ],
        "agents": [
            {
                "key": "incident-supervisor",
                "name": "Incident Supervisor Agent",
                "version": "r21",
                "owner": "Reliability Platform",
                "capabilities": "plan, synthesize, propose",
                "status": "IMPLEMENTED",
                "deployment": "DEPLOYED",
                "identity": "…supervisor@",
                "region": "europe-west1",
            },
            {
                "key": "evidence-agent",
                "name": "Evidence Agent",
                "version": "r17",
                "owner": "Observability",
                "capabilities": "metrics, logs, traces",
                "status": "IMPLEMENTED",
                "deployment": "DEPLOYED",
                "identity": "…evidence@",
                "region": "europe-west1",
            },
            {
                "key": "infrastructure-agent",
                "name": "Infrastructure Agent",
                "version": "r09",
                "owner": "Cloud Platform",
                "capabilities": "resource metadata",
                "status": "IMPLEMENTED",
                "deployment": "DEPLOYED",
                "identity": "…infra@",
                "region": "europe-west1",
            },
            {
                "key": "execution-agent",
                "name": "Execution Agent",
                "version": "implemented · not deployed",
                "owner": "Reliability Platform",
                "capabilities": "private actuator only",
                "status": "IMPLEMENTED",
                "deployment": "NOT_DEPLOYED",
                "identity": "not provisioned",
                "region": "europe-west1",
            },
            {
                "key": "verification-agent",
                "name": "Verification Agent",
                "version": "implemented · not deployed",
                "owner": "SRE",
                "capabilities": "independent oracle",
                "status": "IMPLEMENTED",
                "deployment": "NOT_DEPLOYED",
                "identity": "not provisioned",
                "region": "europe-west1",
            },
            {
                "key": "workspace-agent",
                "name": "Workspace Agent",
                "version": "implemented · not deployed",
                "owner": "Developer Productivity",
                "capabilities": "patch and tests",
                "status": "IMPLEMENTED",
                "deployment": "NOT_DEPLOYED",
                "identity": "not provisioned",
                "region": "europe-west1",
            },
        ],
        "memory": [
            {
                "id": "memc_…9J2K",
                "type": "ROOT_CAUSE",
                "scope": "demo / payments / incident-investigation",
                "status": "PROMOTED",
                "decision": "CONFIRMED",
                "purpose": "INCIDENT_INVESTIGATION",
                "classification": "INTERNAL",
                "review": "AUTOMATIC",
                "created_at": "2026-08-01T12:00:00+00:00",
                "retention": "2026-08-31",
                "source_count": 3,
            },
            {
                "id": "memc_…0P4M",
                "type": "PATTERN",
                "scope": "demo / payments / incident-investigation",
                "status": "QUARANTINED",
                "decision": "UNCONFIRMED",
                "purpose": "INCIDENT_INVESTIGATION",
                "classification": "INTERNAL",
                "review": "HUMAN",
                "created_at": "2026-08-02T09:30:00+00:00",
                "retention": "2026-08-09",
                "source_count": 1,
            },
        ],
        "security": [
            {
                "id": "sec_…fe90",
                "control": "MODEL_ARMOR",
                "severity": "HIGH",
                "event": "PROMPT_CONTENT_BLOCKED",
                "summary": "Instruction-like log content blocked before model context",
                "actor": "evidence-agent",
                "destination": "Evidence Agent",
                "incident": "INC-1042",
                "policy": "armor-template@3",
                "occurred_at": "2026-08-02T12:04:11+00:00",
                "trace": "trace …fe90",
            },
            {
                "id": "sec_…93ad",
                "control": "AGENT_GATEWAY",
                "severity": "WARNING",
                "event": "DESTINATION_DENIED",
                "summary": "Unregistered outbound destination denied",
                "actor": "infrastructure-agent",
                "destination": "external.example",
                "incident": None,
                "policy": None,
                "occurred_at": "2026-08-02T11:52:40+00:00",
                "trace": "trace …93ad",
            },
        ],
        "audit": [
            {
                "sequence": 1442,
                "id": "aud_…88de",
                "time": "2026-08-02T12:06:04+00:00",
                "principal": "coordinator@",
                "event": "ReliabilityCaseOpened",
                "stream_type": "RELIABILITY_CASE",
                "stream_id": "REL-0042",
                "decision": None,
                "trace": None,
                "hash": "sha256:14ac…88de",
            },
            {
                "sequence": 1441,
                "id": "aud_…0f19",
                "time": "2026-08-02T12:05:41+00:00",
                "principal": "verifier@",
                "event": "VerificationPassed",
                "stream_type": "VERIFICATION",
                "stream_id": "VER-1042",
                "decision": "VER-1042",
                "trace": None,
                "hash": "sha256:80db…0f19",
            },
            {
                "sequence": 1440,
                "id": "aud_…a11d",
                "time": "2026-08-02T11:58:13+00:00",
                "principal": "actuator@",
                "event": "MutationReconciled",
                "stream_type": "ACTION",
                "stream_id": "ACT-1042",
                "decision": "ACT-1042",
                "trace": None,
                "hash": "sha256:44c2…a11d",
            },
        ],
        "agent_runs": [],
        "platform": [
            {
                "name": "Agent Registry",
                "lifecycle": "Implemented · cloud pending",
                "health": "HEALTHY",
                "evidence": "LOCAL_VERIFIED",
                "detail": "6 catalog entries · 6 implemented",
                "last_checked": "Local preflight",
                "next_step": "Deploy the registry manifest and capture a cloud receipt.",
            },
            {
                "name": "Agent Runtime",
                "lifecycle": "Implemented · cloud pending",
                "health": "HEALTHY",
                "evidence": "LOCAL_VERIFIED",
                "detail": "Job receipt contract passes",
                "last_checked": "Local adapter check",
                "next_step": "Deploy the runtime adapter and capture an execution receipt.",
            },
            {
                "name": "Memory Bank",
                "lifecycle": "Implemented · cloud pending",
                "health": "HEALTHY",
                "evidence": "LOCAL_VERIFIED",
                "detail": "Exact scope and reconcile-before-create checks pass",
                "last_checked": "Local adapter check",
                "next_step": "Bind the approved Memory Bank scope and capture a cloud receipt.",
            },
            {
                "name": "Agent Identity",
                "lifecycle": "Planned",
                "health": "BLOCKED",
                "evidence": "LOCAL_VERIFIED",
                "detail": "Identity contract is specified; local identities have no authority",
                "last_checked": "Local contract checks",
                "next_step": "Provision regional service identities and verify their audiences.",
            },
            {
                "name": "Agent Gateway",
                "lifecycle": "Planned",
                "health": "BLOCKED",
                "evidence": "LOCAL_VERIFIED",
                "detail": "Default-deny policy is specified; no cloud route is provisioned",
                "last_checked": "Local policy checks",
                "next_step": "Provision the registered routes and capture deny/allow receipts.",
            },
            {
                "name": "Model Armor",
                "lifecycle": "Planned",
                "health": "BLOCKED",
                "evidence": "LOCAL_VERIFIED",
                "detail": "Typed fallback tests pass; cloud template is not provisioned",
                "last_checked": "Local fallback checks",
                "next_step": "Provision the Armor template and run the injection-blocking probe.",
            },
            {
                "name": "Agent Observability",
                "lifecycle": "Implemented · cloud pending",
                "health": "HEALTHY",
                "evidence": "LOCAL_VERIFIED",
                "detail": "OpenTelemetry-shaped traces are emitted locally",
                "last_checked": "Local trace check",
                "next_step": "Deploy the collector and verify end-to-end trace ingestion.",
            },
        ],
    }
